### ISSUE TITLE
[Android] Gradle build failed with signing key

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#471] opened 2015-10-19 07:58 UTC
Build with gradle success if no signing key been specified (debug). It will eventually failed otherwise. 

Original report: http://gsfn.us/t/4snxg

**Comment by bau720123** [comment] 2015-10-19 09:23
hi all
I am the reporter
hope can solve the issue as soon as possible

**Comment by wildabeast** [comment] 2015-10-20 21:24
There are currently issues on Build with plugins that include libraries for both x86 and arm architectures -- specifically the crosswalk plugin in this case. Looking into a fix for this but in the meantime you should source the pgb version of the crosswalk plugin. There's actually two versions of this plugin on build -- one for each architecture (both compile fine both signed and unsigned). The default compiles for arm:

    <gap:plugin name="org.crosswalk.engine" version="1.3.0" source="pgb" />

And to build for x86:

    <gap:plugin name="org.crosswalk.engine.x86" version="1.3.0" source="pgb" />

Working on better support for the mainline npm crosswalk plugin. Stay tuned.

**Comment by bau720123** [comment] 2015-10-21 03:16
hi @wildabeast 
I post some information right here
the bottom...
so...which place should I post in the future will more Easy management ?
the "http://community.phonegap.com/" or "git" ?

**Comment by frederikbosch** [comment] 2015-11-25 17:04
+1

**Comment by kdmon** [comment] 2015-11-29 19:29
+1
See my post here:
http://community.phonegap.com/nitobi/topics/crosswalk-cli-5-2-0-build-issues#reply_16374450

**Comment by frederikbosch** [comment] 2015-11-30 09:33
We have exactly the same problem. Our app cannot be build with an older version of Crosswalk. Only signed builds of the app have the problem.

**Comment by kdmon** [comment] 2015-11-30 10:07
As a temporary workaround, I'm looking into whether it is possible to manually sign the debug package outside of phonegap build. I'll keep you posted.

http://developer.android.com/tools/publishing/app-signing.html#signing-manually

**Comment by kdmon** [comment] 2015-11-30 10:38
Manually signing seems to work once you remove the existing debug signature added by phonegap build. To do this you have have to remove the signature files in META-INF folder inside the package archive. The quickest way of doing this is:

`zip -d name_of_your_package.apk META-INF/\*`

Then you can add your own signature using:

`jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore name_of_your_keystore_file.keystore name_of_your_package.apk name_of_your_alias`

I haven't yet tested if this yields a package that is accepted by Google Play, but it looks promising.

**Comment by frederikbosch** [comment] 2015-12-04 08:58
That is great. Thanks for the thorough explanation. Nonetheless, I would like to see bug being fixed! @wildabeast Any news on the progression? We have problems building all our android apps now.

**Comment by tonijn** [comment] 2015-12-04 12:46
+1

**Comment by dahel** [comment] 2016-01-07 15:07
any news about it?

**Comment by goya** [comment] 2016-01-08 00:50
does someone have a recent app id # that can reproduce this issue?

**Comment by bau720123** [comment] 2016-01-08 03:01
hi @goya 
is you mean my post issue
http://community.phonegap.com/nitobi/topics/-cordova-plugin-crosswalk-webview-still-not-work-with-pgb-gradle
<gap:plugin name="cordova-plugin-crosswalk-webview" source="npm" version="1.4.0" />

```
option1,a keystore file,it will build fail on Android (but I am very sure my keystore file is good to work,because I use it to upload GooglePlay for many times) 
option2,no any ketstore file,it will build success 
```

if yes，my app id is 697726

**Comment by tonijn** [comment] 2016-01-08 08:32
This app id will reproduce the issue 
959643

**Comment by debugerr** [comment] 2016-01-17 16:34
Guys, this issue was reported in October. There are several issues with older crosswalk builds and multiple people do run into them. Can we bump the priority on this one? I have the same problem

**Comment by tonijn** [comment] 2016-01-18 08:35
Yes please bump this one. The amount of people using the newer versions of the crosswalk plugin will only get larger. They will not be able to build their apps using pgb. I myself haven't been able to release an app for Android since october... which is getting problematic.

**Comment by eb1** [comment] 2016-01-18 22:30
+1

**Comment by wildabeast** [comment] 2016-01-18 23:09
Will revisit this and see what we can do to make this work with Build -- but if this is pressing you should pursue @kdmon's signing solution.

**Comment by goya** [comment] 2016-01-22 02:06
fix has been pushed to production.

**Closed by goya** 2016-01-22 02:06 UTC

**Comment by bau720123** [comment] 2016-01-22 05:56
hi @goya 
still build fail when in Android
my appid is 697726
option1,a keystore file,it will build fail on Android (but I am very sure my keystore file is good to work,because I use it to upload GooglePlay for many times) 
option2,no any ketstore file,it will build success

**Comment by goya** [comment] 2016-01-22 06:04
@bau720123 be sure to check out your build logs as it seems it's an error with the translation files.

**Comment by bau720123** [comment] 2016-01-22 07:13
thanks @goya 
it look like the "phonegap-plugin-barcodescanner" plugin problem
when not using crosswalk + "phonegap-plugin-barcodescanner" => android build success
when using crosswalk + "phonegap-plugin-barcodescanner" => android build fail
I will ask the author and try to figure out what the problem

**Comment by bau720123** [comment] 2016-01-22 07:25
hi @goya 
I post a issue right here
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/158
hope domebody can solve it...

**Comment by debugerr** [comment] 2016-01-25 22:40
@goya This is still failing for me: 

:prepareComAndroidSupportSupportV42310Library
:prepareOrgXwalkXwalk_core_library164542119Library
:prepareProjectComPhonegapPluginsFacebookconnectFacebookLibUnspecifiedReleaseLibrary
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareArmv7ReleaseDependencies
:compileArmv7ReleaseAidl
:compileArmv7ReleaseRenderscript
:generateArmv7ReleaseBuildConfig
:generateArmv7ReleaseAssets UP-TO-DATE
:mergeArmv7ReleaseAssets
:createXwalkCommandLineFileArmv7Release
:generateArmv7ReleaseResValues
:generateArmv7ReleaseResources
:mergeArmv7ReleaseResources/project/build/intermediates/exploded-aar/project.com.phonegap.plugins.facebookconnect/FacebookLib/unspecified/release/res/drawable/com_facebook_close.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/build/intermediates/exploded-aar/project.com.phonegap.plugins.facebookconnect/FacebookLib/unspecified/release/res/drawable-ldpi-v4/com_facebook_close.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/build/intermediates/exploded-aar/project.com.phonegap.plugins.facebookconnect/FacebookLib/unspecified/release/res/drawable-hdpi-v4/com_facebook_close.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/build/intermediates/exploded-aar/project.com.phonegap.plugins.facebookconnect/FacebookLib/unspecified/release/res/drawable-xhdpi-v4/com_facebook_close.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:processArmv7ReleaseManifest
:processArmv7ReleaseResourceswarning: string 'menu_settings' has no default translation.

:generateArmv7ReleaseSources
:compileArmv7ReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:lintVitalArmv7Release
:compileArmv7ReleaseNdk
:preDexArmv7Release
:dexArmv7Release
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexArmv7Release'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/android-sdk/build-tools/23.0.1/dx --dex --output /project/build/intermediates/dex/armv7/release --input-list=/project/build/intermediates/tmp/dex/armv7/release/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 37.476 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildRelease,-b,/project/build.gradle,-Dorg.gradle.daemon=true


[Full log](https://build.phonegap.com/apps/1265278/logs/android/build/)

**Comment by Heshyo** [comment] 2016-01-29 09:00
@debugerr I'm compiling **without** a signing key. I have no issue when using CrossWalk plugin version 1.4, but I get the same error with version 1.5 (except it's dexArmv7Debug instead of dexArmv7Release). So I'm not sure if you're error is related to the signature.
