### ISSUE TITLE
[Build] BackupWebStorage No Longer Works

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#338] opened 2014-08-11 17:08 UTC
The following preference is no longer working:
`<preference name="BackupWebStorage" value="none"/ >`

Original implementation:
https://github.com/phonegap/build/issues/191

**Comment by letudiantMP** [comment] 2015-01-05 11:34
Hi 
We have exactly the same issue. Is there any way to solve this problem without use <preference name="BackupWebStorage" value="none"/ > ?

**Comment by mparpaillon** [comment] 2015-01-07 20:31
@wildabeast 

To reproduce this bug,

```
cordova create hello com.hello.www hello
cordova platform add ios
```

Add this to the config.xml file (or local, both are broken)
```
<preference name="BackupWebStorage" value="none" />
```

Add some content to your LocalStorage in index.js. Something like
```
for(var i = 0; i < 5000; i++) {
    localStorage.setItem('wild_' + i, 'Please fix thiiiiiiiiiiiiiis. Thx');
}
```

Build it (Meh)
```
cordova build ios
```

Open the project in Xcode
Build it on a real Device (!= emulator)
When the app has launched
Go to Settings / iCloud / Storage / Manage storage /
Tap on your Device (eg. iPad of wildabeast)
Tap on "Show all apps"

Now wait a few seconds (like 10 or 20... It takes some time to refresh)

And boom the app appears ! The local storage is stored in iCloud. 
The app will be surely rejected (Sometimes "Apple validators" don't see it or tolerate it... I'm not sure)

Hope you can help us with this. 
I've tried a lot of work around (with File API, nothing worked) and I've tested many versions of Cordova (all from 3.6.0-0.2.9)

**Comment by mladenp** [comment] 2015-05-04 10:15
So whats up with this? This is important feature that still doesn't work. A lot of apps get rejected because of large documents folder.

**Comment by ttsda** [comment] 2015-05-08 15:42
Just had two apps rejected because of this issue. Is there any fix?

**Comment by mparpaillon** [comment] 2015-05-08 15:56
You have two possibilities.
Remove Telerik's WKWebView plugin (https://github.com/Telerik-Verified-Plugins/WKWebView/issues/76) or use less LocalStorage.

For now I am not aware of any other option.

**Comment by ttsda** [comment] 2015-05-08 15:58
I am not using that plugin. However, it seemed the problem was with storage in the Documents directory. I am now using `cordova.file.dataDirectory` to store my data.

**Comment by wildabeast** [comment] 2015-05-12 21:00
Created an [issue on the Apache Cordova Jira](https://issues.apache.org/jira/browse/CB-9019).

**Comment by stayted** [comment] 2015-05-16 19:05
9 month for a bug (like this)??? It's crazy!

**Comment by shazron** [comment] 2015-06-19 00:29
There is a misconception on what this setting is.

This is solely for backing up your localStorage/websql storage of the WebView to workaround the changes by Apple in iOS 5.1 and greater, where they are not automatically backed up.

"cloud" means that they are backed up by iCloud. "local" means that it is not backed up by iCloud but backed up in Documents/Backups, with the "Backups" folder flagged to not be backed up by iCloud. "none" will not backup anything to anywhere.

If you store anything in Library or Documents (except Library/Caches), it *will* be backed up by iCloud. For the Cordova File Plugin, to use the Library/Documents folder but not sync it to iCloud, you use the specific extra filesystem: https://github.com/apache/cordova-plugin-file/blob/master/README.md#ios

On a fresh new project, and examining the iCloud data for your app in Settings, you might see that it is enabled and that 0.7kb is being stored. This is your app's preferences file in Library/Preferences, since that does get backed up.

**Comment by wildabeast** [comment] 2015-06-19 22:08
Closing as expected behaviour, see Shazron's clarifications.

**Closed by wildabeast** 2015-06-19 22:08 UTC
Labels: Bug
